/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package frequency;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void hello_should_work() {
        String result = Native.hello("Java");
        assertEquals(result, "Hello, Java!");
    }

    @Test void keep_alive_should_work() {
        Native.keepAlive(this);
    }
}
