// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/input.proto

package io.amplica.graphsdk.models;

public interface ConnectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Connection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 dsnp_user_id = 1;</code>
   * @return The dsnpUserId.
   */
  long getDsnpUserId();

  /**
   * <code>uint32 schema_id = 2;</code>
   * @return The schemaId.
   */
  int getSchemaId();
}
