// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/output.proto

package io.amplica.graphsdk.models;

public interface DsnpGraphEdgesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DsnpGraphEdges)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .DsnpGraphEdges.DsnpGraphEdge edge = 1;</code>
   */
  java.util.List<io.amplica.graphsdk.models.DsnpGraphEdges.DsnpGraphEdge> 
      getEdgeList();
  /**
   * <code>repeated .DsnpGraphEdges.DsnpGraphEdge edge = 1;</code>
   */
  io.amplica.graphsdk.models.DsnpGraphEdges.DsnpGraphEdge getEdge(int index);
  /**
   * <code>repeated .DsnpGraphEdges.DsnpGraphEdge edge = 1;</code>
   */
  int getEdgeCount();
  /**
   * <code>repeated .DsnpGraphEdges.DsnpGraphEdge edge = 1;</code>
   */
  java.util.List<? extends io.amplica.graphsdk.models.DsnpGraphEdges.DsnpGraphEdgeOrBuilder> 
      getEdgeOrBuilderList();
  /**
   * <code>repeated .DsnpGraphEdges.DsnpGraphEdge edge = 1;</code>
   */
  io.amplica.graphsdk.models.DsnpGraphEdges.DsnpGraphEdgeOrBuilder getEdgeOrBuilder(
      int index);
}
