// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge/common/protos/output.proto

package io.amplica.graphsdk.models;

public interface DsnpUsersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DsnpUsers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated uint64 user = 1;</code>
   * @return A list containing the user.
   */
  java.util.List<java.lang.Long> getUserList();
  /**
   * <code>repeated uint64 user = 1;</code>
   * @return The count of user.
   */
  int getUserCount();
  /**
   * <code>repeated uint64 user = 1;</code>
   * @param index The index of the element to return.
   * @return The user at the given index.
   */
  long getUser(int index);
}
