// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/output.proto

package io.amplica.graphsdk.models;

public interface DsnpPublicKeysOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DsnpPublicKeys)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
   */
  java.util.List<io.amplica.graphsdk.models.DsnpPublicKeys.DsnpPublicKey> 
      getPublicKeyList();
  /**
   * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
   */
  io.amplica.graphsdk.models.DsnpPublicKeys.DsnpPublicKey getPublicKey(int index);
  /**
   * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
   */
  int getPublicKeyCount();
  /**
   * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
   */
  java.util.List<? extends io.amplica.graphsdk.models.DsnpPublicKeys.DsnpPublicKeyOrBuilder> 
      getPublicKeyOrBuilderList();
  /**
   * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
   */
  io.amplica.graphsdk.models.DsnpPublicKeys.DsnpPublicKeyOrBuilder getPublicKeyOrBuilder(
      int index);
}
