// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/output.proto

package io.amplica.graphsdk.models;

/**
 * Protobuf type {@code Environment}
 */
public final class Environment extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Environment)
    EnvironmentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Environment.newBuilder() to construct.
  private Environment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Environment() {
    environmentType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Environment();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.amplica.graphsdk.models.Output.internal_static_Environment_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.amplica.graphsdk.models.Output.internal_static_Environment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.amplica.graphsdk.models.Environment.class, io.amplica.graphsdk.models.Environment.Builder.class);
  }

  private int bitField0_;
  public static final int ENVIRONMENT_TYPE_FIELD_NUMBER = 1;
  private int environmentType_ = 0;
  /**
   * <code>.EnvironmentType environment_type = 1;</code>
   * @return The enum numeric value on the wire for environmentType.
   */
  @java.lang.Override public int getEnvironmentTypeValue() {
    return environmentType_;
  }
  /**
   * <code>.EnvironmentType environment_type = 1;</code>
   * @return The environmentType.
   */
  @java.lang.Override public io.amplica.graphsdk.models.EnvironmentType getEnvironmentType() {
    io.amplica.graphsdk.models.EnvironmentType result = io.amplica.graphsdk.models.EnvironmentType.forNumber(environmentType_);
    return result == null ? io.amplica.graphsdk.models.EnvironmentType.UNRECOGNIZED : result;
  }

  public static final int CONFIG_FIELD_NUMBER = 2;
  private io.amplica.graphsdk.models.Config config_;
  /**
   * <code>optional .Config config = 2;</code>
   * @return Whether the config field is set.
   */
  @java.lang.Override
  public boolean hasConfig() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .Config config = 2;</code>
   * @return The config.
   */
  @java.lang.Override
  public io.amplica.graphsdk.models.Config getConfig() {
    return config_ == null ? io.amplica.graphsdk.models.Config.getDefaultInstance() : config_;
  }
  /**
   * <code>optional .Config config = 2;</code>
   */
  @java.lang.Override
  public io.amplica.graphsdk.models.ConfigOrBuilder getConfigOrBuilder() {
    return config_ == null ? io.amplica.graphsdk.models.Config.getDefaultInstance() : config_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (environmentType_ != io.amplica.graphsdk.models.EnvironmentType.MainNet.getNumber()) {
      output.writeEnum(1, environmentType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getConfig());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (environmentType_ != io.amplica.graphsdk.models.EnvironmentType.MainNet.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, environmentType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getConfig());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.amplica.graphsdk.models.Environment)) {
      return super.equals(obj);
    }
    io.amplica.graphsdk.models.Environment other = (io.amplica.graphsdk.models.Environment) obj;

    if (environmentType_ != other.environmentType_) return false;
    if (hasConfig() != other.hasConfig()) return false;
    if (hasConfig()) {
      if (!getConfig()
          .equals(other.getConfig())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENVIRONMENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + environmentType_;
    if (hasConfig()) {
      hash = (37 * hash) + CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getConfig().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.amplica.graphsdk.models.Environment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.amplica.graphsdk.models.Environment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.amplica.graphsdk.models.Environment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.amplica.graphsdk.models.Environment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.amplica.graphsdk.models.Environment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.amplica.graphsdk.models.Environment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.amplica.graphsdk.models.Environment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.amplica.graphsdk.models.Environment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.amplica.graphsdk.models.Environment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.amplica.graphsdk.models.Environment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.amplica.graphsdk.models.Environment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.amplica.graphsdk.models.Environment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.amplica.graphsdk.models.Environment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Environment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Environment)
      io.amplica.graphsdk.models.EnvironmentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.amplica.graphsdk.models.Output.internal_static_Environment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.amplica.graphsdk.models.Output.internal_static_Environment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.amplica.graphsdk.models.Environment.class, io.amplica.graphsdk.models.Environment.Builder.class);
    }

    // Construct using io.amplica.graphsdk.models.Environment.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getConfigFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      environmentType_ = 0;
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.amplica.graphsdk.models.Output.internal_static_Environment_descriptor;
    }

    @java.lang.Override
    public io.amplica.graphsdk.models.Environment getDefaultInstanceForType() {
      return io.amplica.graphsdk.models.Environment.getDefaultInstance();
    }

    @java.lang.Override
    public io.amplica.graphsdk.models.Environment build() {
      io.amplica.graphsdk.models.Environment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.amplica.graphsdk.models.Environment buildPartial() {
      io.amplica.graphsdk.models.Environment result = new io.amplica.graphsdk.models.Environment(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.amplica.graphsdk.models.Environment result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.environmentType_ = environmentType_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.config_ = configBuilder_ == null
            ? config_
            : configBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.amplica.graphsdk.models.Environment) {
        return mergeFrom((io.amplica.graphsdk.models.Environment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.amplica.graphsdk.models.Environment other) {
      if (other == io.amplica.graphsdk.models.Environment.getDefaultInstance()) return this;
      if (other.environmentType_ != 0) {
        setEnvironmentTypeValue(other.getEnvironmentTypeValue());
      }
      if (other.hasConfig()) {
        mergeConfig(other.getConfig());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              environmentType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int environmentType_ = 0;
    /**
     * <code>.EnvironmentType environment_type = 1;</code>
     * @return The enum numeric value on the wire for environmentType.
     */
    @java.lang.Override public int getEnvironmentTypeValue() {
      return environmentType_;
    }
    /**
     * <code>.EnvironmentType environment_type = 1;</code>
     * @param value The enum numeric value on the wire for environmentType to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironmentTypeValue(int value) {
      environmentType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.EnvironmentType environment_type = 1;</code>
     * @return The environmentType.
     */
    @java.lang.Override
    public io.amplica.graphsdk.models.EnvironmentType getEnvironmentType() {
      io.amplica.graphsdk.models.EnvironmentType result = io.amplica.graphsdk.models.EnvironmentType.forNumber(environmentType_);
      return result == null ? io.amplica.graphsdk.models.EnvironmentType.UNRECOGNIZED : result;
    }
    /**
     * <code>.EnvironmentType environment_type = 1;</code>
     * @param value The environmentType to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironmentType(io.amplica.graphsdk.models.EnvironmentType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      environmentType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.EnvironmentType environment_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnvironmentType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      environmentType_ = 0;
      onChanged();
      return this;
    }

    private io.amplica.graphsdk.models.Config config_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.amplica.graphsdk.models.Config, io.amplica.graphsdk.models.Config.Builder, io.amplica.graphsdk.models.ConfigOrBuilder> configBuilder_;
    /**
     * <code>optional .Config config = 2;</code>
     * @return Whether the config field is set.
     */
    public boolean hasConfig() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .Config config = 2;</code>
     * @return The config.
     */
    public io.amplica.graphsdk.models.Config getConfig() {
      if (configBuilder_ == null) {
        return config_ == null ? io.amplica.graphsdk.models.Config.getDefaultInstance() : config_;
      } else {
        return configBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Config config = 2;</code>
     */
    public Builder setConfig(io.amplica.graphsdk.models.Config value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
      } else {
        configBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Config config = 2;</code>
     */
    public Builder setConfig(
        io.amplica.graphsdk.models.Config.Builder builderForValue) {
      if (configBuilder_ == null) {
        config_ = builderForValue.build();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Config config = 2;</code>
     */
    public Builder mergeConfig(io.amplica.graphsdk.models.Config value) {
      if (configBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          config_ != null &&
          config_ != io.amplica.graphsdk.models.Config.getDefaultInstance()) {
          getConfigBuilder().mergeFrom(value);
        } else {
          config_ = value;
        }
      } else {
        configBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Config config = 2;</code>
     */
    public Builder clearConfig() {
      bitField0_ = (bitField0_ & ~0x00000002);
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .Config config = 2;</code>
     */
    public io.amplica.graphsdk.models.Config.Builder getConfigBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Config config = 2;</code>
     */
    public io.amplica.graphsdk.models.ConfigOrBuilder getConfigOrBuilder() {
      if (configBuilder_ != null) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        return config_ == null ?
            io.amplica.graphsdk.models.Config.getDefaultInstance() : config_;
      }
    }
    /**
     * <code>optional .Config config = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.amplica.graphsdk.models.Config, io.amplica.graphsdk.models.Config.Builder, io.amplica.graphsdk.models.ConfigOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.amplica.graphsdk.models.Config, io.amplica.graphsdk.models.Config.Builder, io.amplica.graphsdk.models.ConfigOrBuilder>(
                getConfig(),
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      return configBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Environment)
  }

  // @@protoc_insertion_point(class_scope:Environment)
  private static final io.amplica.graphsdk.models.Environment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.amplica.graphsdk.models.Environment();
  }

  public static io.amplica.graphsdk.models.Environment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Environment>
      PARSER = new com.google.protobuf.AbstractParser<Environment>() {
    @java.lang.Override
    public Environment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Environment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Environment> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.amplica.graphsdk.models.Environment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

