// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge/common/protos/output.proto

package io.amplica.graphsdk.models;

/**
 * Protobuf type {@code SchemaConfig}
 */
public final class SchemaConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SchemaConfig)
    SchemaConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SchemaConfig.newBuilder() to construct.
  private SchemaConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SchemaConfig() {
    dsnpVersion_ = 0;
    connectionType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SchemaConfig();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.amplica.graphsdk.models.Output.internal_static_SchemaConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.amplica.graphsdk.models.Output.internal_static_SchemaConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.amplica.graphsdk.models.SchemaConfig.class, io.amplica.graphsdk.models.SchemaConfig.Builder.class);
  }

  public static final int DSNP_VERSION_FIELD_NUMBER = 1;
  private int dsnpVersion_;
  /**
   * <code>.DsnpVersion dsnp_version = 1;</code>
   * @return The enum numeric value on the wire for dsnpVersion.
   */
  @java.lang.Override public int getDsnpVersionValue() {
    return dsnpVersion_;
  }
  /**
   * <code>.DsnpVersion dsnp_version = 1;</code>
   * @return The dsnpVersion.
   */
  @java.lang.Override public io.amplica.graphsdk.models.DsnpVersion getDsnpVersion() {
    @SuppressWarnings("deprecation")
    io.amplica.graphsdk.models.DsnpVersion result = io.amplica.graphsdk.models.DsnpVersion.valueOf(dsnpVersion_);
    return result == null ? io.amplica.graphsdk.models.DsnpVersion.UNRECOGNIZED : result;
  }

  public static final int CONNECTION_TYPE_FIELD_NUMBER = 2;
  private int connectionType_;
  /**
   * <code>.ConnectionType connection_type = 2;</code>
   * @return The enum numeric value on the wire for connectionType.
   */
  @java.lang.Override public int getConnectionTypeValue() {
    return connectionType_;
  }
  /**
   * <code>.ConnectionType connection_type = 2;</code>
   * @return The connectionType.
   */
  @java.lang.Override public io.amplica.graphsdk.models.ConnectionType getConnectionType() {
    @SuppressWarnings("deprecation")
    io.amplica.graphsdk.models.ConnectionType result = io.amplica.graphsdk.models.ConnectionType.valueOf(connectionType_);
    return result == null ? io.amplica.graphsdk.models.ConnectionType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dsnpVersion_ != io.amplica.graphsdk.models.DsnpVersion.Version1_0.getNumber()) {
      output.writeEnum(1, dsnpVersion_);
    }
    if (connectionType_ != io.amplica.graphsdk.models.ConnectionType.FollowPublic.getNumber()) {
      output.writeEnum(2, connectionType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dsnpVersion_ != io.amplica.graphsdk.models.DsnpVersion.Version1_0.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, dsnpVersion_);
    }
    if (connectionType_ != io.amplica.graphsdk.models.ConnectionType.FollowPublic.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, connectionType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.amplica.graphsdk.models.SchemaConfig)) {
      return super.equals(obj);
    }
    io.amplica.graphsdk.models.SchemaConfig other = (io.amplica.graphsdk.models.SchemaConfig) obj;

    if (dsnpVersion_ != other.dsnpVersion_) return false;
    if (connectionType_ != other.connectionType_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DSNP_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + dsnpVersion_;
    hash = (37 * hash) + CONNECTION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + connectionType_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.amplica.graphsdk.models.SchemaConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.amplica.graphsdk.models.SchemaConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.amplica.graphsdk.models.SchemaConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.amplica.graphsdk.models.SchemaConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.amplica.graphsdk.models.SchemaConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.amplica.graphsdk.models.SchemaConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.amplica.graphsdk.models.SchemaConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.amplica.graphsdk.models.SchemaConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.amplica.graphsdk.models.SchemaConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.amplica.graphsdk.models.SchemaConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.amplica.graphsdk.models.SchemaConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.amplica.graphsdk.models.SchemaConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.amplica.graphsdk.models.SchemaConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SchemaConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SchemaConfig)
      io.amplica.graphsdk.models.SchemaConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.amplica.graphsdk.models.Output.internal_static_SchemaConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.amplica.graphsdk.models.Output.internal_static_SchemaConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.amplica.graphsdk.models.SchemaConfig.class, io.amplica.graphsdk.models.SchemaConfig.Builder.class);
    }

    // Construct using io.amplica.graphsdk.models.SchemaConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dsnpVersion_ = 0;

      connectionType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.amplica.graphsdk.models.Output.internal_static_SchemaConfig_descriptor;
    }

    @java.lang.Override
    public io.amplica.graphsdk.models.SchemaConfig getDefaultInstanceForType() {
      return io.amplica.graphsdk.models.SchemaConfig.getDefaultInstance();
    }

    @java.lang.Override
    public io.amplica.graphsdk.models.SchemaConfig build() {
      io.amplica.graphsdk.models.SchemaConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.amplica.graphsdk.models.SchemaConfig buildPartial() {
      io.amplica.graphsdk.models.SchemaConfig result = new io.amplica.graphsdk.models.SchemaConfig(this);
      result.dsnpVersion_ = dsnpVersion_;
      result.connectionType_ = connectionType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.amplica.graphsdk.models.SchemaConfig) {
        return mergeFrom((io.amplica.graphsdk.models.SchemaConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.amplica.graphsdk.models.SchemaConfig other) {
      if (other == io.amplica.graphsdk.models.SchemaConfig.getDefaultInstance()) return this;
      if (other.dsnpVersion_ != 0) {
        setDsnpVersionValue(other.getDsnpVersionValue());
      }
      if (other.connectionType_ != 0) {
        setConnectionTypeValue(other.getConnectionTypeValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              dsnpVersion_ = input.readEnum();

              break;
            } // case 8
            case 16: {
              connectionType_ = input.readEnum();

              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int dsnpVersion_ = 0;
    /**
     * <code>.DsnpVersion dsnp_version = 1;</code>
     * @return The enum numeric value on the wire for dsnpVersion.
     */
    @java.lang.Override public int getDsnpVersionValue() {
      return dsnpVersion_;
    }
    /**
     * <code>.DsnpVersion dsnp_version = 1;</code>
     * @param value The enum numeric value on the wire for dsnpVersion to set.
     * @return This builder for chaining.
     */
    public Builder setDsnpVersionValue(int value) {
      
      dsnpVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.DsnpVersion dsnp_version = 1;</code>
     * @return The dsnpVersion.
     */
    @java.lang.Override
    public io.amplica.graphsdk.models.DsnpVersion getDsnpVersion() {
      @SuppressWarnings("deprecation")
      io.amplica.graphsdk.models.DsnpVersion result = io.amplica.graphsdk.models.DsnpVersion.valueOf(dsnpVersion_);
      return result == null ? io.amplica.graphsdk.models.DsnpVersion.UNRECOGNIZED : result;
    }
    /**
     * <code>.DsnpVersion dsnp_version = 1;</code>
     * @param value The dsnpVersion to set.
     * @return This builder for chaining.
     */
    public Builder setDsnpVersion(io.amplica.graphsdk.models.DsnpVersion value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      dsnpVersion_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.DsnpVersion dsnp_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDsnpVersion() {
      
      dsnpVersion_ = 0;
      onChanged();
      return this;
    }

    private int connectionType_ = 0;
    /**
     * <code>.ConnectionType connection_type = 2;</code>
     * @return The enum numeric value on the wire for connectionType.
     */
    @java.lang.Override public int getConnectionTypeValue() {
      return connectionType_;
    }
    /**
     * <code>.ConnectionType connection_type = 2;</code>
     * @param value The enum numeric value on the wire for connectionType to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionTypeValue(int value) {
      
      connectionType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ConnectionType connection_type = 2;</code>
     * @return The connectionType.
     */
    @java.lang.Override
    public io.amplica.graphsdk.models.ConnectionType getConnectionType() {
      @SuppressWarnings("deprecation")
      io.amplica.graphsdk.models.ConnectionType result = io.amplica.graphsdk.models.ConnectionType.valueOf(connectionType_);
      return result == null ? io.amplica.graphsdk.models.ConnectionType.UNRECOGNIZED : result;
    }
    /**
     * <code>.ConnectionType connection_type = 2;</code>
     * @param value The connectionType to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionType(io.amplica.graphsdk.models.ConnectionType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      connectionType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ConnectionType connection_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectionType() {
      
      connectionType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SchemaConfig)
  }

  // @@protoc_insertion_point(class_scope:SchemaConfig)
  private static final io.amplica.graphsdk.models.SchemaConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.amplica.graphsdk.models.SchemaConfig();
  }

  public static io.amplica.graphsdk.models.SchemaConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SchemaConfig>
      PARSER = new com.google.protobuf.AbstractParser<SchemaConfig>() {
    @java.lang.Override
    public SchemaConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SchemaConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SchemaConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.amplica.graphsdk.models.SchemaConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

