// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/output.proto

package io.amplica.graphsdk.models;

public interface UpdatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Updates)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Updates.Update update = 1;</code>
   */
  java.util.List<io.amplica.graphsdk.models.Updates.Update> 
      getUpdateList();
  /**
   * <code>repeated .Updates.Update update = 1;</code>
   */
  io.amplica.graphsdk.models.Updates.Update getUpdate(int index);
  /**
   * <code>repeated .Updates.Update update = 1;</code>
   */
  int getUpdateCount();
  /**
   * <code>repeated .Updates.Update update = 1;</code>
   */
  java.util.List<? extends io.amplica.graphsdk.models.Updates.UpdateOrBuilder> 
      getUpdateOrBuilderList();
  /**
   * <code>repeated .Updates.Update update = 1;</code>
   */
  io.amplica.graphsdk.models.Updates.UpdateOrBuilder getUpdateOrBuilder(
      int index);
}
