
/*
    @dsnp/graphsdk-node
    Entry point for graphsdk.node bindings. This file exposes types and functions
    from the native module to the JS layer.
*/
import fs from 'fs';
import path from 'path';


// function to load the native module generated by neon
function loadNative() {
    // Development version
    if (fs.existsSync(path.join(__dirname, '/../../dsnp_graph_sdk.node'))) {
        return require(path.join(__dirname, '/../../dsnp_graph_sdk.node'))
    }
    throw new Error(
      `Unable to load dsnp_graph_sdk.node, probably your system (${process.arch}-${process.platform}) with Node.js ${process.version} is not supported.`
    );
}

// load the native module
const native = loadNative();
