/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class frequency_Native */

#ifndef _Included_frequency_Native
#define _Included_frequency_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     frequency_Native
 * Method:    keepAlive
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_frequency_Native_keepAlive
  (JNIEnv *, jclass, jobject);

/*
 * Class:     frequency_Native
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_frequency_Native_hello
  (JNIEnv *, jclass, jstring);

/*
 * Class:     frequency_Native
 * Method:    loggerInitialize
 * Signature: (ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_frequency_Native_loggerInitialize
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
