// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge/common/protos/output.proto

package io.projectliberty.graphsdk.models;

/**
 * Protobuf type {@code DsnpPublicKeys}
 */
public final class DsnpPublicKeys extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DsnpPublicKeys)
    DsnpPublicKeysOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DsnpPublicKeys.newBuilder() to construct.
  private DsnpPublicKeys(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DsnpPublicKeys() {
    publicKey_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DsnpPublicKeys();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.projectliberty.graphsdk.models.Output.internal_static_DsnpPublicKeys_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.projectliberty.graphsdk.models.Output.internal_static_DsnpPublicKeys_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.projectliberty.graphsdk.models.DsnpPublicKeys.class, io.projectliberty.graphsdk.models.DsnpPublicKeys.Builder.class);
  }

  public interface DsnpPublicKeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DsnpPublicKeys.DsnpPublicKey)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes key = 1;</code>
     * @return The key.
     */
    com.google.protobuf.ByteString getKey();

    /**
     * <code>uint64 key_id = 2;</code>
     * @return The keyId.
     */
    long getKeyId();
  }
  /**
   * Protobuf type {@code DsnpPublicKeys.DsnpPublicKey}
   */
  public static final class DsnpPublicKey extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DsnpPublicKeys.DsnpPublicKey)
      DsnpPublicKeyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DsnpPublicKey.newBuilder() to construct.
    private DsnpPublicKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DsnpPublicKey() {
      key_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DsnpPublicKey();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.projectliberty.graphsdk.models.Output.internal_static_DsnpPublicKeys_DsnpPublicKey_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.projectliberty.graphsdk.models.Output.internal_static_DsnpPublicKeys_DsnpPublicKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.class, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }

    public static final int KEY_ID_FIELD_NUMBER = 2;
    private long keyId_ = 0L;
    /**
     * <code>uint64 key_id = 2;</code>
     * @return The keyId.
     */
    @java.lang.Override
    public long getKeyId() {
      return keyId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!key_.isEmpty()) {
        output.writeBytes(1, key_);
      }
      if (keyId_ != 0L) {
        output.writeUInt64(2, keyId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!key_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, key_);
      }
      if (keyId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, keyId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey)) {
        return super.equals(obj);
      }
      io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey other = (io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (getKeyId()
          != other.getKeyId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + KEY_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getKeyId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DsnpPublicKeys.DsnpPublicKey}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DsnpPublicKeys.DsnpPublicKey)
        io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.projectliberty.graphsdk.models.Output.internal_static_DsnpPublicKeys_DsnpPublicKey_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.projectliberty.graphsdk.models.Output.internal_static_DsnpPublicKeys_DsnpPublicKey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.class, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.Builder.class);
      }

      // Construct using io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = com.google.protobuf.ByteString.EMPTY;
        keyId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.projectliberty.graphsdk.models.Output.internal_static_DsnpPublicKeys_DsnpPublicKey_descriptor;
      }

      @java.lang.Override
      public io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey getDefaultInstanceForType() {
        return io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.getDefaultInstance();
      }

      @java.lang.Override
      public io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey build() {
        io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey buildPartial() {
        io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey result = new io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.keyId_ = keyId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey) {
          return mergeFrom((io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey other) {
        if (other == io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.getDefaultInstance()) return this;
        if (other.getKey() != com.google.protobuf.ByteString.EMPTY) {
          setKey(other.getKey());
        }
        if (other.getKeyId() != 0L) {
          setKeyId(other.getKeyId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                keyId_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }
      /**
       * <code>bytes key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }

      private long keyId_ ;
      /**
       * <code>uint64 key_id = 2;</code>
       * @return The keyId.
       */
      @java.lang.Override
      public long getKeyId() {
        return keyId_;
      }
      /**
       * <code>uint64 key_id = 2;</code>
       * @param value The keyId to set.
       * @return This builder for chaining.
       */
      public Builder setKeyId(long value) {
        
        keyId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 key_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        keyId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DsnpPublicKeys.DsnpPublicKey)
    }

    // @@protoc_insertion_point(class_scope:DsnpPublicKeys.DsnpPublicKey)
    private static final io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey();
    }

    public static io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DsnpPublicKey>
        PARSER = new com.google.protobuf.AbstractParser<DsnpPublicKey>() {
      @java.lang.Override
      public DsnpPublicKey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DsnpPublicKey> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DsnpPublicKey> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int PUBLIC_KEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey> publicKey_;
  /**
   * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey> getPublicKeyList() {
    return publicKey_;
  }
  /**
   * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKeyOrBuilder> 
      getPublicKeyOrBuilderList() {
    return publicKey_;
  }
  /**
   * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
   */
  @java.lang.Override
  public int getPublicKeyCount() {
    return publicKey_.size();
  }
  /**
   * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
   */
  @java.lang.Override
  public io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey getPublicKey(int index) {
    return publicKey_.get(index);
  }
  /**
   * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
   */
  @java.lang.Override
  public io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKeyOrBuilder getPublicKeyOrBuilder(
      int index) {
    return publicKey_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < publicKey_.size(); i++) {
      output.writeMessage(1, publicKey_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < publicKey_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, publicKey_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.projectliberty.graphsdk.models.DsnpPublicKeys)) {
      return super.equals(obj);
    }
    io.projectliberty.graphsdk.models.DsnpPublicKeys other = (io.projectliberty.graphsdk.models.DsnpPublicKeys) obj;

    if (!getPublicKeyList()
        .equals(other.getPublicKeyList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPublicKeyCount() > 0) {
      hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKeyList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.projectliberty.graphsdk.models.DsnpPublicKeys parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.projectliberty.graphsdk.models.DsnpPublicKeys parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.projectliberty.graphsdk.models.DsnpPublicKeys parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.projectliberty.graphsdk.models.DsnpPublicKeys parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.projectliberty.graphsdk.models.DsnpPublicKeys parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.projectliberty.graphsdk.models.DsnpPublicKeys parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.projectliberty.graphsdk.models.DsnpPublicKeys parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.projectliberty.graphsdk.models.DsnpPublicKeys parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.projectliberty.graphsdk.models.DsnpPublicKeys parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.projectliberty.graphsdk.models.DsnpPublicKeys parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.projectliberty.graphsdk.models.DsnpPublicKeys parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.projectliberty.graphsdk.models.DsnpPublicKeys parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.projectliberty.graphsdk.models.DsnpPublicKeys prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DsnpPublicKeys}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DsnpPublicKeys)
      io.projectliberty.graphsdk.models.DsnpPublicKeysOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.projectliberty.graphsdk.models.Output.internal_static_DsnpPublicKeys_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.projectliberty.graphsdk.models.Output.internal_static_DsnpPublicKeys_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.projectliberty.graphsdk.models.DsnpPublicKeys.class, io.projectliberty.graphsdk.models.DsnpPublicKeys.Builder.class);
    }

    // Construct using io.projectliberty.graphsdk.models.DsnpPublicKeys.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (publicKeyBuilder_ == null) {
        publicKey_ = java.util.Collections.emptyList();
      } else {
        publicKey_ = null;
        publicKeyBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.projectliberty.graphsdk.models.Output.internal_static_DsnpPublicKeys_descriptor;
    }

    @java.lang.Override
    public io.projectliberty.graphsdk.models.DsnpPublicKeys getDefaultInstanceForType() {
      return io.projectliberty.graphsdk.models.DsnpPublicKeys.getDefaultInstance();
    }

    @java.lang.Override
    public io.projectliberty.graphsdk.models.DsnpPublicKeys build() {
      io.projectliberty.graphsdk.models.DsnpPublicKeys result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.projectliberty.graphsdk.models.DsnpPublicKeys buildPartial() {
      io.projectliberty.graphsdk.models.DsnpPublicKeys result = new io.projectliberty.graphsdk.models.DsnpPublicKeys(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.projectliberty.graphsdk.models.DsnpPublicKeys result) {
      if (publicKeyBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          publicKey_ = java.util.Collections.unmodifiableList(publicKey_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.publicKey_ = publicKey_;
      } else {
        result.publicKey_ = publicKeyBuilder_.build();
      }
    }

    private void buildPartial0(io.projectliberty.graphsdk.models.DsnpPublicKeys result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.projectliberty.graphsdk.models.DsnpPublicKeys) {
        return mergeFrom((io.projectliberty.graphsdk.models.DsnpPublicKeys)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.projectliberty.graphsdk.models.DsnpPublicKeys other) {
      if (other == io.projectliberty.graphsdk.models.DsnpPublicKeys.getDefaultInstance()) return this;
      if (publicKeyBuilder_ == null) {
        if (!other.publicKey_.isEmpty()) {
          if (publicKey_.isEmpty()) {
            publicKey_ = other.publicKey_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePublicKeyIsMutable();
            publicKey_.addAll(other.publicKey_);
          }
          onChanged();
        }
      } else {
        if (!other.publicKey_.isEmpty()) {
          if (publicKeyBuilder_.isEmpty()) {
            publicKeyBuilder_.dispose();
            publicKeyBuilder_ = null;
            publicKey_ = other.publicKey_;
            bitField0_ = (bitField0_ & ~0x00000001);
            publicKeyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPublicKeyFieldBuilder() : null;
          } else {
            publicKeyBuilder_.addAllMessages(other.publicKey_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey m =
                  input.readMessage(
                      io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.parser(),
                      extensionRegistry);
              if (publicKeyBuilder_ == null) {
                ensurePublicKeyIsMutable();
                publicKey_.add(m);
              } else {
                publicKeyBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey> publicKey_ =
      java.util.Collections.emptyList();
    private void ensurePublicKeyIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        publicKey_ = new java.util.ArrayList<io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey>(publicKey_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.Builder, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKeyOrBuilder> publicKeyBuilder_;

    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public java.util.List<io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey> getPublicKeyList() {
      if (publicKeyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(publicKey_);
      } else {
        return publicKeyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public int getPublicKeyCount() {
      if (publicKeyBuilder_ == null) {
        return publicKey_.size();
      } else {
        return publicKeyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey getPublicKey(int index) {
      if (publicKeyBuilder_ == null) {
        return publicKey_.get(index);
      } else {
        return publicKeyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public Builder setPublicKey(
        int index, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey value) {
      if (publicKeyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePublicKeyIsMutable();
        publicKey_.set(index, value);
        onChanged();
      } else {
        publicKeyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public Builder setPublicKey(
        int index, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.Builder builderForValue) {
      if (publicKeyBuilder_ == null) {
        ensurePublicKeyIsMutable();
        publicKey_.set(index, builderForValue.build());
        onChanged();
      } else {
        publicKeyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public Builder addPublicKey(io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey value) {
      if (publicKeyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePublicKeyIsMutable();
        publicKey_.add(value);
        onChanged();
      } else {
        publicKeyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public Builder addPublicKey(
        int index, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey value) {
      if (publicKeyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePublicKeyIsMutable();
        publicKey_.add(index, value);
        onChanged();
      } else {
        publicKeyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public Builder addPublicKey(
        io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.Builder builderForValue) {
      if (publicKeyBuilder_ == null) {
        ensurePublicKeyIsMutable();
        publicKey_.add(builderForValue.build());
        onChanged();
      } else {
        publicKeyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public Builder addPublicKey(
        int index, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.Builder builderForValue) {
      if (publicKeyBuilder_ == null) {
        ensurePublicKeyIsMutable();
        publicKey_.add(index, builderForValue.build());
        onChanged();
      } else {
        publicKeyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public Builder addAllPublicKey(
        java.lang.Iterable<? extends io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey> values) {
      if (publicKeyBuilder_ == null) {
        ensurePublicKeyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, publicKey_);
        onChanged();
      } else {
        publicKeyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public Builder clearPublicKey() {
      if (publicKeyBuilder_ == null) {
        publicKey_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        publicKeyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public Builder removePublicKey(int index) {
      if (publicKeyBuilder_ == null) {
        ensurePublicKeyIsMutable();
        publicKey_.remove(index);
        onChanged();
      } else {
        publicKeyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.Builder getPublicKeyBuilder(
        int index) {
      return getPublicKeyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKeyOrBuilder getPublicKeyOrBuilder(
        int index) {
      if (publicKeyBuilder_ == null) {
        return publicKey_.get(index);  } else {
        return publicKeyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public java.util.List<? extends io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKeyOrBuilder> 
         getPublicKeyOrBuilderList() {
      if (publicKeyBuilder_ != null) {
        return publicKeyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(publicKey_);
      }
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.Builder addPublicKeyBuilder() {
      return getPublicKeyFieldBuilder().addBuilder(
          io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.getDefaultInstance());
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.Builder addPublicKeyBuilder(
        int index) {
      return getPublicKeyFieldBuilder().addBuilder(
          index, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.getDefaultInstance());
    }
    /**
     * <code>repeated .DsnpPublicKeys.DsnpPublicKey public_key = 1;</code>
     */
    public java.util.List<io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.Builder> 
         getPublicKeyBuilderList() {
      return getPublicKeyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.Builder, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKeyOrBuilder> 
        getPublicKeyFieldBuilder() {
      if (publicKeyBuilder_ == null) {
        publicKeyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKey.Builder, io.projectliberty.graphsdk.models.DsnpPublicKeys.DsnpPublicKeyOrBuilder>(
                publicKey_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        publicKey_ = null;
      }
      return publicKeyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DsnpPublicKeys)
  }

  // @@protoc_insertion_point(class_scope:DsnpPublicKeys)
  private static final io.projectliberty.graphsdk.models.DsnpPublicKeys DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.projectliberty.graphsdk.models.DsnpPublicKeys();
  }

  public static io.projectliberty.graphsdk.models.DsnpPublicKeys getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DsnpPublicKeys>
      PARSER = new com.google.protobuf.AbstractParser<DsnpPublicKeys>() {
    @java.lang.Override
    public DsnpPublicKeys parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DsnpPublicKeys> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DsnpPublicKeys> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.projectliberty.graphsdk.models.DsnpPublicKeys getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

