// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge/common/protos/output.proto

package io.projectliberty.graphsdk.models;

/**
 * Protobuf type {@code DsnpUsers}
 */
public final class DsnpUsers extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DsnpUsers)
    DsnpUsersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DsnpUsers.newBuilder() to construct.
  private DsnpUsers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DsnpUsers() {
    user_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DsnpUsers();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.projectliberty.graphsdk.models.Output.internal_static_DsnpUsers_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.projectliberty.graphsdk.models.Output.internal_static_DsnpUsers_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.projectliberty.graphsdk.models.DsnpUsers.class, io.projectliberty.graphsdk.models.DsnpUsers.Builder.class);
  }

  public static final int USER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList user_;
  /**
   * <code>repeated uint64 user = 1;</code>
   * @return A list containing the user.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getUserList() {
    return user_;
  }
  /**
   * <code>repeated uint64 user = 1;</code>
   * @return The count of user.
   */
  public int getUserCount() {
    return user_.size();
  }
  /**
   * <code>repeated uint64 user = 1;</code>
   * @param index The index of the element to return.
   * @return The user at the given index.
   */
  public long getUser(int index) {
    return user_.getLong(index);
  }
  private int userMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getUserList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(userMemoizedSerializedSize);
    }
    for (int i = 0; i < user_.size(); i++) {
      output.writeUInt64NoTag(user_.getLong(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < user_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt64SizeNoTag(user_.getLong(i));
      }
      size += dataSize;
      if (!getUserList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      userMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.projectliberty.graphsdk.models.DsnpUsers)) {
      return super.equals(obj);
    }
    io.projectliberty.graphsdk.models.DsnpUsers other = (io.projectliberty.graphsdk.models.DsnpUsers) obj;

    if (!getUserList()
        .equals(other.getUserList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUserCount() > 0) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUserList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.projectliberty.graphsdk.models.DsnpUsers parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.projectliberty.graphsdk.models.DsnpUsers parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.projectliberty.graphsdk.models.DsnpUsers parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.projectliberty.graphsdk.models.DsnpUsers parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.projectliberty.graphsdk.models.DsnpUsers parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.projectliberty.graphsdk.models.DsnpUsers parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.projectliberty.graphsdk.models.DsnpUsers parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.projectliberty.graphsdk.models.DsnpUsers parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.projectliberty.graphsdk.models.DsnpUsers parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.projectliberty.graphsdk.models.DsnpUsers parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.projectliberty.graphsdk.models.DsnpUsers parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.projectliberty.graphsdk.models.DsnpUsers parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.projectliberty.graphsdk.models.DsnpUsers prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DsnpUsers}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DsnpUsers)
      io.projectliberty.graphsdk.models.DsnpUsersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.projectliberty.graphsdk.models.Output.internal_static_DsnpUsers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.projectliberty.graphsdk.models.Output.internal_static_DsnpUsers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.projectliberty.graphsdk.models.DsnpUsers.class, io.projectliberty.graphsdk.models.DsnpUsers.Builder.class);
    }

    // Construct using io.projectliberty.graphsdk.models.DsnpUsers.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      user_ = emptyLongList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.projectliberty.graphsdk.models.Output.internal_static_DsnpUsers_descriptor;
    }

    @java.lang.Override
    public io.projectliberty.graphsdk.models.DsnpUsers getDefaultInstanceForType() {
      return io.projectliberty.graphsdk.models.DsnpUsers.getDefaultInstance();
    }

    @java.lang.Override
    public io.projectliberty.graphsdk.models.DsnpUsers build() {
      io.projectliberty.graphsdk.models.DsnpUsers result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.projectliberty.graphsdk.models.DsnpUsers buildPartial() {
      io.projectliberty.graphsdk.models.DsnpUsers result = new io.projectliberty.graphsdk.models.DsnpUsers(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.projectliberty.graphsdk.models.DsnpUsers result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        user_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.user_ = user_;
    }

    private void buildPartial0(io.projectliberty.graphsdk.models.DsnpUsers result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.projectliberty.graphsdk.models.DsnpUsers) {
        return mergeFrom((io.projectliberty.graphsdk.models.DsnpUsers)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.projectliberty.graphsdk.models.DsnpUsers other) {
      if (other == io.projectliberty.graphsdk.models.DsnpUsers.getDefaultInstance()) return this;
      if (!other.user_.isEmpty()) {
        if (user_.isEmpty()) {
          user_ = other.user_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureUserIsMutable();
          user_.addAll(other.user_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              long v = input.readUInt64();
              ensureUserIsMutable();
              user_.addLong(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureUserIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                user_.addLong(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList user_ = emptyLongList();
    private void ensureUserIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        user_ = mutableCopy(user_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated uint64 user = 1;</code>
     * @return A list containing the user.
     */
    public java.util.List<java.lang.Long>
        getUserList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(user_) : user_;
    }
    /**
     * <code>repeated uint64 user = 1;</code>
     * @return The count of user.
     */
    public int getUserCount() {
      return user_.size();
    }
    /**
     * <code>repeated uint64 user = 1;</code>
     * @param index The index of the element to return.
     * @return The user at the given index.
     */
    public long getUser(int index) {
      return user_.getLong(index);
    }
    /**
     * <code>repeated uint64 user = 1;</code>
     * @param index The index to set the value at.
     * @param value The user to set.
     * @return This builder for chaining.
     */
    public Builder setUser(
        int index, long value) {
      
      ensureUserIsMutable();
      user_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint64 user = 1;</code>
     * @param value The user to add.
     * @return This builder for chaining.
     */
    public Builder addUser(long value) {
      
      ensureUserIsMutable();
      user_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint64 user = 1;</code>
     * @param values The user to add.
     * @return This builder for chaining.
     */
    public Builder addAllUser(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureUserIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, user_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint64 user = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUser() {
      user_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DsnpUsers)
  }

  // @@protoc_insertion_point(class_scope:DsnpUsers)
  private static final io.projectliberty.graphsdk.models.DsnpUsers DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.projectliberty.graphsdk.models.DsnpUsers();
  }

  public static io.projectliberty.graphsdk.models.DsnpUsers getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DsnpUsers>
      PARSER = new com.google.protobuf.AbstractParser<DsnpUsers>() {
    @java.lang.Override
    public DsnpUsers parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DsnpUsers> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DsnpUsers> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.projectliberty.graphsdk.models.DsnpUsers getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

