// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge/common/protos/output.proto

package io.projectliberty.graphsdk.models;

/**
 * Protobuf enum {@code EnvironmentType}
 */
public enum EnvironmentType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MainNet = 0;</code>
   */
  MainNet(0),
  /**
   * <code>TestnetPaseo = 1;</code>
   */
  TestnetPaseo(1),
  /**
   * <code>Rococo = 2;</code>
   */
  Rococo(2),
  /**
   * <code>Dev = 3;</code>
   */
  Dev(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MainNet = 0;</code>
   */
  public static final int MainNet_VALUE = 0;
  /**
   * <code>TestnetPaseo = 1;</code>
   */
  public static final int TestnetPaseo_VALUE = 1;
  /**
   * <code>Rococo = 2;</code>
   */
  public static final int Rococo_VALUE = 2;
  /**
   * <code>Dev = 3;</code>
   */
  public static final int Dev_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EnvironmentType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EnvironmentType forNumber(int value) {
    switch (value) {
      case 0: return MainNet;
      case 1: return TestnetPaseo;
      case 2: return Rococo;
      case 3: return Dev;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EnvironmentType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EnvironmentType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EnvironmentType>() {
          public EnvironmentType findValueByNumber(int number) {
            return EnvironmentType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.projectliberty.graphsdk.models.Output.getDescriptor().getEnumTypes().get(3);
  }

  private static final EnvironmentType[] VALUES = values();

  public static EnvironmentType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EnvironmentType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:EnvironmentType)
}

