// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge/common/protos/input.proto

package io.projectliberty.graphsdk.models;

public interface ImportBundlesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImportBundles)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ImportBundles.ImportBundle bundles = 1;</code>
   */
  java.util.List<io.projectliberty.graphsdk.models.ImportBundles.ImportBundle> 
      getBundlesList();
  /**
   * <code>repeated .ImportBundles.ImportBundle bundles = 1;</code>
   */
  io.projectliberty.graphsdk.models.ImportBundles.ImportBundle getBundles(int index);
  /**
   * <code>repeated .ImportBundles.ImportBundle bundles = 1;</code>
   */
  int getBundlesCount();
  /**
   * <code>repeated .ImportBundles.ImportBundle bundles = 1;</code>
   */
  java.util.List<? extends io.projectliberty.graphsdk.models.ImportBundles.ImportBundleOrBuilder> 
      getBundlesOrBuilderList();
  /**
   * <code>repeated .ImportBundles.ImportBundle bundles = 1;</code>
   */
  io.projectliberty.graphsdk.models.ImportBundles.ImportBundleOrBuilder getBundlesOrBuilder(
      int index);
}
