// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge/common/protos/input.proto

package io.projectliberty.graphsdk.models;

public interface KeyDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:KeyData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 index = 1;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>bytes content = 2;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
