// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge/common/protos/output.proto

package io.projectliberty.graphsdk.models;

public interface SchemaConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SchemaConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.DsnpVersion dsnp_version = 1;</code>
   * @return The enum numeric value on the wire for dsnpVersion.
   */
  int getDsnpVersionValue();
  /**
   * <code>.DsnpVersion dsnp_version = 1;</code>
   * @return The dsnpVersion.
   */
  io.projectliberty.graphsdk.models.DsnpVersion getDsnpVersion();

  /**
   * <code>.ConnectionType connection_type = 2;</code>
   * @return The enum numeric value on the wire for connectionType.
   */
  int getConnectionTypeValue();
  /**
   * <code>.ConnectionType connection_type = 2;</code>
   * @return The connectionType.
   */
  io.projectliberty.graphsdk.models.ConnectionType getConnectionType();
}
