/*
 * This build file was generated by the Gradle 'init' task.
 *
 * This generated file contains a commented-out sample Kotlin project to get you started.
 * For more details take a look at the Kotlin Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/7.0/userguide/tutorial_kotlin_projects.html
 */

// Apply the Kotlin JVM plugin to add support for Kotlin
plugins {
    // Apply the kotlin-jvm plugin for Kotlin JVM projects.
    kotlin("jvm") version "1.6.21"
    id("java")
}
java.sourceCompatibility = JavaVersion.VERSION_17

// Use the 'repositories' block to declare where to find your dependencies
repositories {
    // Use 'jcenter' for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()

    // Add the GitHub Packages repository as a source for resolving dependencies
	maven {
		name = "GithubPackages"
		url = uri("https://maven.pkg.github.com/LibertyDSNP/graph-sdk")
		credentials {
			username = project.findProperty("gpr.user") as String? ?: System.getenv("GITHUB_ACTOR")
			password = project.findProperty("gpr.key") as String? ?: System.getenv("GITHUB_TOKEN")
		}
	}
}

// In this section, you declare the dependencies for your production and test code
dependencies {
    // The production code uses the SLF4J logging API at compile time
    implementation("org.slf4j:slf4j-api:1.7.25")

    // Declare the dependency for JUnit for your tests
    testImplementation("io.github.hakky54:logcaptor:2.9.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

    // Add your own dependency for the library from GitHub Packages
    implementation("io.amplica.graphsdk:lib:0.0.1-SNAPSHOT")


}

// Use the 'test' task to run tests
tasks.test {
    // Use JUnit Platform for executing tests
    useJUnitPlatform()
}
